name: diape
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  camera: ^0.10.2+2
  image_picker: ^0.8.7+3
  flutter_launcher_icons: ^0.11.0

  cupertino_icons: ^1.0.8

flutter_icons:
  android: true
  ios: false
  image_path: "assets/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/profile_image.png

